<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_fulltext_api_menu() {
  $items = array();

  $items['islandora/fulltext/%/%'] = array (
    'page callback' => 'islandora_fulltext_api_responder',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
  );

  return $items;
}

function islandora_fulltext_api_responder($pid, $format) {
  $object = islandora_object_load($pid);
  if (!$object) {
    $response = "Error: '{$pid}' not a valid PID.";
    echo $response;
    drupal_exit();
  }
  else if (!in_array($object->models[0], array('islandora:bookCModel'))) { // Later add islandora:newspaperCModel
    $response = "Error: '{$pid}' not a book or newspaper.";
    echo $response;
    drupal_exit();
  }
  else if ($format != 'ocr' && $format != 'hocr') {
    $response = "Error: '{$format}' not a valid format. Only 'ocr' and 'hocr' allowed.";
    echo $response;
    drupal_exit();
  }
  else {
    $filename = islandora_fulltext_api_get_fulltext($object, $format);
    $mime = ($format == 'ocr' ? "text/plain" : "text/html");
    drupal_add_http_header('Content-type', "{$mime}; charset=utf-8");
    drupal_add_http_header('Content-Disposition', "attachment; filename='{$filename}'");
    echo file_get_contents('temporary://' . $filename);
  }

}

function islandora_fulltext_api_get_fulltext($object, $format) {
  $pids = islandora_fulltext_api_get_page_pids($object->id);
  $filename = islandora_fulltext_api_aggregate_page_fulltext($object, $pids, $format);
  return $filename;
}

function islandora_fulltext_api_get_page_pids($pid) {
  $query = <<<EOQ
SELECT ?pid ?seq
FROM <#ri>
WHERE {
  ?pid <http://islandora.ca/ontology/relsext#isPageOf> <info:fedora/{$pid}> .
  ?pid <http://islandora.ca/ontology/relsext#isPageNumber> ?seq 
}
EOQ;
  $connection = islandora_get_tuque_connection();
  $results = $connection->repository->ri->sparqlQuery($query);
  $pids = array();
  foreach ($results as $result) {
    $pids[] = $result['pid']['value'];
  }

  return $pids;
}

function islandora_fulltext_api_aggregate_page_fulltext($parent, $pids, $format) {
  $fulltext = ""; 
  foreach ($pids as $pid) {
    $object = islandora_object_load($pid);
    $datastream = strtoupper($format);
    $fulltext .= $object["{$datastream}"]->content;
    $fulltext .= ($format == 'ocr' ? "\n" : "<br/>");
  }

  $replaced_pid = str_replace(":", "_", $parent->id);
  $extension = ($format == 'ocr' ? "txt" : "html");
  $filename = "{$replaced_pid}_{$format}.{$extension}";
  $file = file_unmanaged_save_data($fulltext, "temporary://" . $filename, FILE_EXISTS_REPLACE);
  return $filename;
}
