<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

/**
 * Implements hook_menu().
 */
function islandora_fulltext_api_menu() {
  $items = array();

  $items['islandora/fulltext/%'] = array (
    'page callback' => 'islandora_fulltext_api_responder',
    'page arguments' => array(2),
    'access callback' => TRUE,
  );

  return $items;
}

function islandora_fulltext_api_responder($pid) {
  $object = islandora_object_load($pid);
  if (!$object) {
    $response = "Error: '{$pid}' not a valid PID.";
  }
  else {
    $response = islandora_fulltext_api_get_fulltext($object);
  }

  echo $response; 
  drupal_exit();
}

function islandora_fulltext_api_get_fulltext($object) {
  $pids = islandora_fulltext_api_get_page_pids($pid);
  $fulltext = islandora_fulltext_api_aggregate_page_fulltext($pids);
  return $fulltext;
}

function islandora_fulltext_api_get_page_pids($pid) {
  
}


function islandora_fulltext_api_aggregate_page_fulltext($pids) {
}
